intellectual_names = {
    'ויסלבה שימבורסקה':'Wisława Szymborska',
    'אריך פרום':'Erich Fromm',
    'אלברט איינשטיין':'Albert Einstein',
    'נועם חומסקי':'Noam Chomsky',
    'זיגמונד פרויד':'Sigmund Freud',
    "סלבוי ז׳יז׳ק":'Slavoj Zizek',
    'מילטון פרידמן':'Milton Friedman',
    'חנה ארנדט':'Hannah Arendt',
    'מקס ובר':'Max Weber',
    'אלן גרינשפן':'Alan Greenspan',
    'דזמונד טוטו':'Desmond Tutu',
    'ויקטור פרנקל':'Viktor Frankl',
    'אנטוניו גראמשי':'Antonio Gramsci',
    'קרל פופר':'Karl Popper',
    "ז׳ק דרידה":'Jacques Derrida',
    'אברהם מאסלו':'Abraham Maslow',
    'אומברטו אקו':'Umberto Echo',
    'דניאל כהנמן':'Daniel Kahneman',
    "ז׳ק לקאן":'Jacques Lacan',
    'מרשל מקלוהאן':'Marshall McLuhan',
    'אריק אריקסון':'Erik Erikson',
    'מרגרט מיד':'Margaret Mead',
    'רולאן בארת׳':'Roland Barthes',
    'הרברט מרקוזה':'Herbert Marcusa', # Herbert Marcuse
    'תאודור אדורנו':'Theodor Adorno',
    'ליאו שטראוס':'Leopo Strauss', # Leo Strauss
    'רונאלד פישר':'Ronald Fisher',
    'מישל פוקו':'Michel Foucault',
    "ג׳ודית באטלר":'Judith Butler',
    'ברוך שפינוזה':'Baruch Spinoza',
    'לודוויג ויטגנשטיין':'Ludwig Wittgenstein',
    'פרידריך ניטשה':'Friedrich Nietzsche',
    'אמה גולדמן':'Emma Goldman',
    'לב טולסטוי':'Lev Tolstoi',
    "ז'אן בודריאר":'Jean Baudrillard',
    'רנה דקארט':'Renéi Descart', # René Descartes
    'פרנץ פנון':'Frantz Fanon',
    'ויליאם אדוארד בורגהרד דו בויז':'Du Bois',
    'לואי אלתוסר':'Louis Althusser',
    'יורגן הברמאס':'Jürgen Habermas',
    'גי דבור':'Guy Debord',
    'אדוארד סעיד':'Edward Saaid',
    'זיגמונט באומן':'Zygmunt Bauman',
    'אווה אילוז':'Eva Illouz',
    'גוטפריד לייבניץ':'Gottfried Leibniz',
    'סוזן סונטג':'Susan Sontag',
    'אודרי לורד':'Audrep Lorde' # Audre Lorde
}
